# ... below the joy parameters
joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

Kendall_node:
  ros__parameters:
    
    axis_linear:  # Left thumb stick vertical
      x: 4
    scale_linear:
      x: 5.0
    scale_linear_turbo:
      x: 3.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 9.0
    scale_angular_turbo:
      yaw: 4.0

    require_enable_button: false

kylie_node:
  ros__parameters:
    
    axis_linear:  # Left thumb stick vertical
      x: 0
    scale_linear:
      x: 5.0
    scale_linear_turbo:
      x: 4.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 5.0
    scale_angular_turbo:
      yaw: 4.0

    require_enable_button: false
  